<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joueurs SYSTEM [
    <!ELEMENT joueurs (joueur+)>
    <!ELEMENT joueur (id, nom, email, mot_de_passe, points)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT mot_de_passe (#PCDATA)>
    <!ELEMENT points (#PCDATA)>
]>
<joueurs>
    <joueur>
        <id>1</id>
        <nom>utilisateur1</nom>
        <email>utilisateur1@example.com</email>
        <mot_de_passe>mot_de_passe1</mot_de_passe>
        <points>0</points>
    </joueur>
</joueurs>



